- name: user creation
  hosts: local
  connection: local
  become: yes
  tasks:
  - name: to check user exists or not
    ansible.builtin.command: id roboshop
    register: redirect_output
    ignore_errors: true
  - name: to print output
    ansible.builtin.debug:
      msg: "{{ redirect_output }}"

  - name: to create user
    ansible.builtin.command: useradd roboshop
    when: redirect_output.rc != 0  
