- name: For functions
  hosts: local
  connection: local
  tasks:
  - name: redirect the output
    ansible.builtin.shell: ls -ltr > /tmp/output.txt
    register: redirect_output
  - name: to print above output
    ansible.builtin.debug:
      msg: "redirect_output"

  - name: redirect the output
    ansible.builtin.command: ls -ltr
    register: redirect_output
  - name: to print above output
    ansible.builtin.debug:
      msg: "redirect_output"